language: python
python:
- '3.6'
install: pip install -r requirements.txt
script: nosetests
services: postgresql
before_script:
- psql -c 'CREATE DATABASE resties_test;' -U postgres
- psql -c "CREATE USER resties_admin with PASSWORD 'asdf4321';" -U postgres
env:
  global:
  - APP_SETTINGS="project._config.TestingConfig"
  - TEST_SETTINGS="project._config.TestingConfig"
  - RESTIES_DB_URL="postgresql://localhost/resties_test"
  - TEST_DB_URL="postgresql://localhost/resties_test"
  matrix:
  - secure: JbpbGl2sRZMV7PRlU7m4JqPriYg+QdtLISBk7A6yYJp6ZcRLdl99R/Zglc+62ltOuHJrrXQ7P8WQporPa7/1wsWxzbkl7UgDCnB8dCOdwSApezV3Dc/pN2rsDOmPj72ENufxErDB8nLfOvJfjJedwKK7wT4LjMwUxnyfxpvmuZBI3ufCYju4tVhugIACrQgkG1/rdZNQxFdH1pNtuCxd5rb0sSMnEwpt4L+fRGakwAVg8APJFo0y7xuNKXAp6j8XuhCI3H8s5ytTcQ/jrBnNFW59WBQJ7rwucTzu5Q9Sr7ObV3Eha+fsh+wW9jAMMzxdXtjg5REzWI0U26QqnR6cYDV0TV6DuPnATSaql9f7YCcb7UB8qf/99wbBqKP2pTBnj4vyQuJ/70SM8T0Xdva+RxQny5gOzvIOD2vYmyFg35swlhtAfowkF+4ij9+YVvjPXSb42aEHlh1i/nHA70kHnB9hYqk7GZUP3+pSJTNmDTE/+1lG7s1RMNzE/rVbmVQSjt504a08tzp1BTgpusYlJU025/hAgv28IDQexzv/RmWV6997J1bcKyewmgXEBA2l4HX4m192aPYj5QfA6IXKnvlLLcl2PpWu1f3w8hckYXiWO+6oo6l61Lri7nH50D0r1KAHFOv8uaK4h6TpARc1IRahoU7j3H/uaPBEO13SrFU=
deploy:
  provider: heroku
  api_key:
    secure: uWNtfkG5hmP9gPJfS2hr/k7zll2R660/P9xk1GP1Nz3tLSfXC68lHDIOH1hQUiWAvpy4TVfztmV+SlvKyDMKQPg58xQZ9DdSFymSXMYl3GNENlKZ0XBnwDKR+cpRYH3sVdYScAm5/PVr+BqI32hocwVcQ49L8yELBp4BkCpeoKrh8b+y4o4kK4Di+P/RvNEcpYp2Q/tNggBnHgjqVHI6CK5kAjzJCdZetaRbDd4rG522bntBUZaCx/vym7gLIKiombdog222GQxk95q6oPhS6OvYnDxG8tyrBf4kli5Fgrlr63fRitEHkB5J1IowNvNXHgrS2/bXTvzksLAcQv2OL7tnBCZiMfBuSog1A6/vCh2I2JGYkome7Sj8C1gzt6tK66uUXlmSoBeUL+H2de1oB+0XE8qb+yJX6rKm2jZrNYwXwrqgamCS6OnzmPwD8BleyOtVvS5nmw4b861Ee2fITHLjtyzZh2HktqYqL8a9ybfvq9K0hvvkPxfrgm80zXMdqUOAQT7SyYB82e+PK8oOXB53ap3QDmmZqA5FkSkrwUHadjbpZbSR+9pmg+A1v67WDnucK4flyz2P4GEAB5N1qn608oJvWnrMTa2ISqiphMGEMPROK9wR/DFzeEk5TNQYPa8OayY/Blqxp3YtN3jgDvrBrzC6aPq66amjrvo5dvo=
  app: resties
  skip_cleanup: true
