language: python
python:
- '3.6'
intall: pip install -r requirements.txt
script: nosetests
env:
  matrix:
    - secure: JbpbGl2sRZMV7PRlU7m4JqPriYg+QdtLISBk7A6yYJp6ZcRLdl99R/Zglc+62ltOuHJrrXQ7P8WQporPa7/1wsWxzbkl7UgDCnB8dCOdwSApezV3Dc/pN2rsDOmPj72ENufxErDB8nLfOvJfjJedwKK7wT4LjMwUxnyfxpvmuZBI3ufCYju4tVhugIACrQgkG1/rdZNQxFdH1pNtuCxd5rb0sSMnEwpt4L+fRGakwAVg8APJFo0y7xuNKXAp6j8XuhCI3H8s5ytTcQ/jrBnNFW59WBQJ7rwucTzu5Q9Sr7ObV3Eha+fsh+wW9jAMMzxdXtjg5REzWI0U26QqnR6cYDV0TV6DuPnATSaql9f7YCcb7UB8qf/99wbBqKP2pTBnj4vyQuJ/70SM8T0Xdva+RxQny5gOzvIOD2vYmyFg35swlhtAfowkF+4ij9+YVvjPXSb42aEHlh1i/nHA70kHnB9hYqk7GZUP3+pSJTNmDTE/+1lG7s1RMNzE/rVbmVQSjt504a08tzp1BTgpusYlJU025/hAgv28IDQexzv/RmWV6997J1bcKyewmgXEBA2l4HX4m192aPYj5QfA6IXKnvlLLcl2PpWu1f3w8hckYXiWO+6oo6l61Lri7nH50D0r1KAHFOv8uaK4h6TpARc1IRahoU7j3H/uaPBEO13SrFU=
