"""users_search_radius_no_null

Revision ID: 4af81849f99f
Revises: cc593476c53e
Create Date: 2017-11-20 12:46:08.049281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af81849f99f'
down_revision = 'cc593476c53e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'search_radius',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'search_radius',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
