"""Added fname and lname to user model.

Revision ID: ca8c06aff16c
Revises: 
Create Date: 2017-10-02 21:08:22.893235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8c06aff16c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lname')
    op.drop_column('users', 'fname')
    # ### end Alembic commands ###
