"""search_radius_null

Revision ID: cc593476c53e
Revises: ca8c06aff16c
Create Date: 2017-11-20 12:43:55.791239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc593476c53e'
down_revision = 'ca8c06aff16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('search_radius', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'search_radius')
    # ### end Alembic commands ###
